export const OPENROUTER_MODEL = 'deepseek/deepseek-v4-flash';
export const OPENROUTER_VISION_MODEL = 'google/gemini-2.5-flash';
export const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';

export const BLOCK_TYPES = [
  'text',
  'tasks',
  'people',
  'projects',
  'stats',
  'chart',
  'table',
  'insights',
  'activity',
  'columns',
];

const seriesItem = {
  type: 'object',
  additionalProperties: false,
  required: ['label', 'value', 'color'],
  properties: {
    label: { type: 'string' },
    value: { type: 'number' },
    color: { type: 'string' },
  },
};

const statItem = {
  type: 'object',
  additionalProperties: false,
  required: ['label', 'value', 'tone'],
  properties: {
    label: { type: 'string' },
    value: { type: 'string' },
    tone: { type: 'string', enum: ['default', 'warn', 'ok', ''] },
  },
};

const ACTION_OPS = [
  'create_project',
  'create_task',
  'update_task',
  'delete_task',
  'move_task',
  'create_board',
  'update_board',
  'delete_board',
  'create_sprint',
  'close_sprint',
];

const actionItem = {
  type: 'object',
  additionalProperties: false,
  required: [
    'op',
    'id',
    'name',
    'key',
    'title',
    'description',
    'color',
    'icon',
    'projectId',
    'boardId',
    'sprintId',
    'columnId',
    'statusKey',
    'priority',
    'assigneeId',
    'dueDate',
    'estimateHours',
    'progress',
    'labels',
    'kind',
    'frequencyDays',
    'startsOn',
    'endsOn',
  ],
  properties: {
    op: { type: 'string', enum: ACTION_OPS },
    id: { type: 'string', description: 'ID da tarefa/board/sprint ao editar. Vazio em create.' },
    name: { type: 'string', description: 'Nome do projeto, board ou sprint' },
    key: { type: 'string', description: 'Sigla do projeto, 3 letras' },
    title: { type: 'string', description: 'Titulo da tarefa' },
    description: { type: 'string' },
    color: { type: 'string' },
    icon: { type: 'string', description: 'sparkle|pulse|device|shield|layers|target' },
    projectId: { type: 'string', description: 'ID, key ou nome do projeto' },
    boardId: { type: 'string', description: 'ID ou nome do board' },
    sprintId: { type: 'string', description: 'ID ou nome do sprint' },
    columnId: { type: 'string' },
    statusKey: { type: 'string', description: 'backlog|in_progress|review|blocked|done' },
    priority: { type: 'string', description: 'urgent|high|medium|low' },
    assigneeId: { type: 'string', description: 'ID ou nome da pessoa' },
    dueDate: { type: 'string', description: 'YYYY-MM-DD' },
    estimateHours: { type: 'string' },
    progress: { type: 'string' },
    labels: { type: 'string', description: 'labels separados por virgula' },
    kind: { type: 'string', description: 'normal|dynamic' },
    frequencyDays: { type: 'string', description: 'Frequencia do board dinamico em dias, ex 7' },
    startsOn: { type: 'string', description: 'Inicio do sprint YYYY-MM-DD' },
    endsOn: { type: 'string', description: 'Fim do sprint YYYY-MM-DD' },
  },
};

/** Schema estrito para structured outputs do OpenRouter. Campos vazios = nao usar. */
export const REPLY_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['answer', 'suggestions', 'blocks', 'actions'],
  properties: {
    answer: { type: 'string', description: 'Resposta curta em portugues, 1 a 4 frases.' },
    suggestions: {
      type: 'array',
      items: { type: 'string' },
      description: 'Ate 4 proximos chips de pergunta.',
    },
    actions: {
      type: 'array',
      items: actionItem,
      maxItems: 12,
      description: 'Mutacoes reais. Vazio se for so consulta. Ate 12 por turno.',
    },
    blocks: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['type', 'title', 'text', 'ids', 'chartType', 'series', 'stats', 'columns', 'rows'],
        properties: {
          type: { type: 'string', enum: BLOCK_TYPES },
          title: { type: 'string' },
          text: { type: 'string' },
          ids: {
            type: 'array',
            items: { type: 'string' },
            description: 'IDs reais do catalogo (tarefas, pessoas, projetos, insights, colunas).',
          },
          chartType: { type: 'string', enum: ['bar', 'donut', 'line', 'none'] },
          series: { type: 'array', items: seriesItem },
          stats: { type: 'array', items: statItem },
          columns: { type: 'array', items: { type: 'string' } },
          rows: { type: 'array', items: { type: 'array', items: { type: 'string' } } },
        },
      },
    },
  },
};

export function buildSystemPrompt() {
  return [
    'Voce e o Kanbot, copiloto de um kanban multi-produto: cada produto (projeto) tem varios boards.',
    'Board normal = tarefas continuas. Board dinamico = sprints que viram na frequencia (ex. 7 dias).',
    'Responda SEMPRE com JSON no schema kanbot_reply. Nunca invente IDs: use so os do catalogo.',
    'Escreva em portugues, tom direto, sem markdown de codigo.',
    '',
    'Quando usar cada bloco:',
    '- tasks: listar, priorizar, atrasadas, bloqueadas, de uma pessoa ou projeto. ids = task.id',
    '- people: carga, donos, sobrecarga, time. ids = member.id',
    '- projects: saude, progresso, comparar projetos. ids = project.id',
    '- stats: metricas (atrasadas, WIP, velocity). stats[{label,value,tone}]',
    '- chart: distribuicao, carga, tendencia. chartType bar|donut|line + series[{label,value,color}]',
    '- table: comparativos tabulares. columns + rows',
    '- insights: sugerir acao ja existente. ids = insight.id',
    '- activity: movimento recente. text descreve, ids opcionais',
    '- columns: colunas/WIP. ids = column.id se houver no catalogo',
    '- text: so complemento. Evite repetir o campo answer.',
    '',
    'Regras:',
    '- Prefira 1 a 3 blocos visuais alem do answer.',
    '- Cores: urgent/blocked #E5484D, high/in_progress #F5A524, review #BFE3F2, done #8FE3B0, backlog #6E7A85.',
    '- Se nao souber, diga o que o catalogo mostra. Nao alucine cards.',
    '- suggestions: perguntas naturais que o usuario pode clicar.',
    '- Campos nao usados: string vazia, array vazio, chartType "none".',
    '',
    'MUTACOES (actions): o sistema executa de verdade. So preencha actions se o usuario pediu criar/editar/excluir/mover.',
    '- Se o usuario pediu criar, editar, mover ou excluir, actions NAO pode ser []. Nao diga que fez se o array estiver vazio.',
    '- create_project: name obrigatorio. key com 3 letras. description/color/icon opcionais.',
    '- create_task: title obrigatorio (nunca vazio) + projectId (id, key ou nome). boardId (id ou nome) ou o board da tela. columnId ou statusKey.',
    '- Se o usuario listar tarefas (virgulas, "e", ";"), uma create_task por item. title = o texto de cada item, nao "Tarefa sem titulo".',
    '- "nele", "nela", "nesse", "neste projeto" = threadProjectId do contexto (projeto da conversa), nao o da tela se forem diferentes.',
    '- update_task: id = UUID ou titulo. So preencha campos que mudam.',
    '- move_task: id + columnId ou statusKey. Pode mudar de board com boardId.',
    '- delete_task: id da tarefa.',
    '- create_board: projectId + name + kind normal|dynamic. Se dynamic, frequencyDays (7, 14, 30).',
    '- update_board: id do board. name/kind/frequencyDays.',
    '- delete_board: id. Nao apague o ultimo board do produto.',
    '- create_sprint: boardId de um board dinamico (se o produto so tem board normal e o usuario pediu sprint, crie um board dinamico primeiro).',
    '- close_sprint: id do sprint ativo. Incompletas vao para o proximo sprint na mesma coluna.',
    '- Em um mesmo turno, crie o projeto/board primeiro; nas tasks seguintes use a key/nome novo.',
    '- Nao invente UUID. Consultas (resumo, quem, prazos) devem ter actions: [].',
    '',
    'CONTEXTO DE TELA: quando vier um bloco CONTEXTO ATUAL DA TELA, ele manda na desambiguacao.',
    'Se o usuario anexar um print do monitor, use a imagem com o catalogo. Nao invente texto ilegivel.',
    '- "esta tarefa", "essa tarefa", "isso" = openTask do contexto. Use o id dela em update_task/move_task/delete_task.',
    '- "este projeto", "aqui", "nesta tela" = projectId da TELA. "nele"/"nesse projeto" = threadProjectId se existir.',
    '- "neste board" = boardId do contexto. Sem board citado, use o board da tela ou o default do produto.',
    '- Comece pelo que esta na tela antes de trazer o resto do workspace.',
  ].join('\n');
}
